import React from 'react'
import Title from './Title'

const dataList=[
{title:'Definitions',content:`“Agreement” means all terms and conditions found in this form and on the document titled Face Page. “You” or “your” means the person identified as the renter in this Agreement, each person signing this Agreement, each Authorized Driver and each person or organization to whom charges are billed by us at its or the renter’s direction. All persons referred to as “you’ or “your” are jointly and severally bound by this Agreement. “We”, “our” or “us” means the business organization named in this Agreement that is renting the Vehicle to you. “Authorized Driver” means the renter and each additional driver listed by us on this Agreement, provided that each such person has a valid driver’s license and is at least age 18. Only Authorized Drivers are permitted to operate the Vehicle ‘‘Vehicle” means the automobile or truck identified in this Agreement and each vehicle we substitute for it, and all its tires, tools, accessories, equipment, keys and Vehicle documents. This Vehicle may be equipped with an electronic locator device. “CDW” means Collision Damage Waiver. “Physical Damage” means damage to, or loss of, the Vehicle caused by collision or upset. Physical Damage does not include comprehensive damage such as damage to or loss of the Vehicle due to theft, vandalism, act of nature, riot or civil disturbance, hail, flood or fire or other loss not caused by collision or upset. “Loss of Use” means the loss of our ability to use the Vehicle for any purpose due to damage to it or loss of it during this rental, including uses other than for rental, such as display for rent, display for sale, opportunity to upgrade, opportunity to sell, or transportation of employees. Damages for Loss of Use are often difficult to determine with precision. Therefore, you and we agree that Loss of Use will be calculated by multiplying the number of days from the date the Vehicle is damaged until it is replaced or repaired times 80% of the daily rental rate. You and we agree this formula represents a reasonable estimate of actual damages and not a penalty. “Diminished Value” means the actual cash value of the Vehicle just prior to damage or loss less the value of the Vehicle after repair or replacement. “Vehicle License Cost Recovery Fee” means our good faith estimate of the daily charge necessary for to recover our actual total annual costs to license, title, register, plate, inspect or pay excise tax costs on our rental fleet.`},
{title:`Rental, Indemnity and Warranties.`,content:`This is a contract for rental of the Vehicle. We may repossess the Vehicle at your expense without notice to you, if the Vehicle is abandoned or used in violation of law or this Agreement. You agree to indemnify us, defend us and hold us harmless from all claims, liability, costs and attorney fees we incur resulting from or arising out of this rental and your use of the Vehicle. We make no warranties, express, implied or apparent, regarding the Vehicle, no warranty of merchantability and no warranty that the Vehicle is fit for a particular purpose.`},
{title:`Condition and Return of Vehicle`,content:`You must return the Vehicle to the location specified in this Agreement, on the date and time specified in this Agreement, and in the same condition that you received it except for ordinary wear. If You return the Vehicle more than 1 hour after the date and time specified in this Agreement, You will be charged for an additional half day of rental. If You return the Vehicle more than 3 hours after the date and time specified in this Agreement, You will be charged for an additional full day of rental. Service to the Vehicle or replacement of parts or accessories during the rental must have our prior approval. You must check and maintain all fluid levels and return the Vehicle with the same amount of fuel as when rented.`},
{title:`Delivery and Return with a Concierge.`,content:`If a concierge has already been dispatched to deliver or pick up a Vehicle, You have up to 30 minutes to meet him at the location and time specified in this Agreement. After 30 minutes grace period, You will incur a charge of $50 and an additional charge of $50 per every half hour after that until You arrive.`},
{title:`Prohibited Uses of Vehicle.`,content:`You may not use or permit the Vehicle to be used: (a) by anyone who is not an Authorized Driver; (b) for any illegal purpose or in any illegal manner; (c) to push or tow anything, or carry persons or property for hire, unless specifically authorized elsewhere in this Agreement; (d) while an Authorized Driver is under the influence of alcohol, illegal drugs or chemicals as defined and determined under the law of the State where the Vehicle is being operated; (e) to participate in any speed contest; (f) to carry more passengers than the number of seat belts in the Vehicle; (g) to drive outside the United States or Canada, unless specifically authorized elsewhere in this Agreement; (h) to drive on unpaved roads, beaches, off-road areas, or in any area where we prohibit driving; (i) to drive with a tire that is flat, has a puncture`},        
{title:`Responsibility for Damage or Loss`,content:`Reporting to Police; Responsibility for Tolls and Traffic Violations. You are responsible for all damage to, or loss or theft of, the Vehicle, including damage caused by weather, road conditions and acts of nature, whether or not you are at fault. You are responsible for the cost of repair, or the actual cash retail value of the Vehicle on the date of the loss if the Vehicle is not repairable or if we elect not to repair the Vehicle. You are also responsible for Loss of Use, Diminished Value, and our administrative expenses incurred processing the claim. You must report all accidents or incidents of theft and vandalism to us and the police as soon as you discover them. You are responsible for paying to the appropriate 3rd party all tolls, parking, traffic and toll violations, toll evasion fines, citations, other fees, penalties, forfeitures, court costs, towing, and storage charges occurring during this rental. If you fail to pay the charging entities and we pay all or any of the charges on your behalf, you will reimburse us for all such costs and, in addition, pay us an administrative fee of $50 for each such charge.`},
{title:`Accidental Damage Collision Damage Waiver.`,content:`If you purchase CDW, we waive your responsibility for a portion of Physical Damage to the Vehicle. We will not waive this right if the Vehicle was rented or an Authorized Driver was approved as a result of fraudulent information provided to us, or if the damage or loss: (a) is caused intentionally, willfully or wantonly by an Authorized Driver; (b) occurs while an Authorized Driver operates the Vehicle while legally intoxicated or under the influence of any illegal drug or chemical as defined and determined under the law of the State where the damage occurs; (c) is caused while you are engaged in any speed contest; (d) occurs while pushing or towing anything, or carrying persons or property for hire, unless specifically authorized elsewhere in this Agreement; (e) occurs while the Vehicle is being driven outside the United States or Canada, unless specifically authorized elsewhere in this Agreement; (f) occurs while the Vehicle is being driven, with the renter’s permission or accession, by anyone other than an Authorized Driver; (g) is a result of the commission of a felony by an Authorized Driver.`},
{title:`Injury to Others;`,content:`Insurance. You are responsible for all injury, damage and loss you cause to others. You agree to provide liability, collision and comprehensive insurance covering you, us, and the Vehicle. Where state law requires us to provide auto liability insurance, or if you have no auto liability insurance, we provide auto liability insurance (the “Policy”) that is secondary to all other valid and collectible insurance whether primary, secondary, excess or contingent. The Policy provides bodily injury and property damage liability coverage with limits no higher than minimum levels prescribed by the vehicular financial responsibility laws of the State whose laws apply to the loss. You and we reject PIP, medical payments, no-fault and uninsured and under-insured motorist coverage, where permitted by law. The Policy is void if you breach this Agreement or if you fail to cooperate in a loss investigation conducted by us or our insurer. Giving the Vehicle to an unauthorized driver terminates coverage under the Policy.`},
{title:`Charges.`,content:`You permit us to reserve against your credit/debit card at the time of rental a reasonable amount in addition to the estimated charges. You will pay us at or before the conclusion of this rental or on demand all charges noted on the Face Page of this Agreement, plus: (a) a mileage charge based on our experience if the odometer is tampered with or disconnected; (b) fuel and a refueling charge, if you return the Vehicle with less fuel than when rented; (c) a charge for the total cost of all tolls billed to your Vehicle's E-ZPass throughout the term of your rental; (d) all expenses we incur recovering the Vehicle, if it is not returned as promised; (e) all costs, including pre- and post-judgment attorney fees, we incur collecting payment from you or otherwise enforcing or defending our rights under this Agreement; (f) a 2% per month late payment fee, or the maximum amount allowed by law, on all amounts paid after the rental concludes; (g) $50 or the maximum amount permitted by law, whichever is greater, if you pay us with a check returned unpaid for any reason; and (h) a reasonable fee not to exceed $350 to clean the Vehicle if returned substantially less clean than when rented. All charges are subject to our final audit. If errors in computation of the charges are discovered after the close of this transaction, you authorize us to correct the charges with your credit/debit card issuer.`},
{title:`Deposit.`,content:`We may use your deposit to pay all amounts owed to us under this Agreement.`},
{title:`Your Property.`,content:`You release us, our agents and employees from all claims for loss of and damage to your personal property or that of another person, that we received, handled or stored, or that was left or carried in or on the Vehicle or in a service vehicle or in our offices, whether or not the loss or damage was caused by our negligence or was otherwise our responsibility.`},
{title:`Breach of Agreement.`,content:`The acts listed in paragraph 5, above, are prohibited uses of the Vehicle and breaches of this Agreement. You waive all recourse against us for criminal reports or prosecutions that we take against you that arise out of your breach of this Agreement.`},
{title:`Extension of Rental Period.`,content:`If you wish to extend the rental period, you must submit a request in the "My Account" menu of the RealCar website (www.realcar.nyc) by using the "extend my order" function; all requests for any extensions to the term of your order are subject to our approval. If we have not approved the requested rental extension, the Vehicle must be returned at the date and time and location specified by the initial Agreement. This Agreement constitutes the entire agreement between you and us. All prior representations and agreements between you and us regarding this rental are void.`},
{title:`Miscellaneous.`,content:`A waiver by us of a breach of this Agreement is not a waiver of an additional breach or waiver of the performance of your obligations under this Agreement. Our acceptance of payment from you or our failure, refusal or neglect to exercise our rights under this Agreement does not constitute a waiver of any other provision of this Agreement. Unless prohibited by law, you release us from all liability for consequential, special or punitive damages in connection with this rental or the reservation of a vehicle. If a provision of this Agreement is deemed void or unenforceable, the remaining provisions are valid and enforceable.`},
{title:`Cancellation Policy.`,content:`Customers may cancel 72 hours prior to the reservation start date for a full refund. If a cancellation is made within 72 hours of the reservation start date and time, we can only provide an e-credit which can be applied toward future rental reservations with RealCar.`},
{title:`RealCar Connect SMS Service.`,content:`The RealCar Connect service provides a one-time confirmation code to clients for phone number verification purposes. We also send informational messages about the status of deliveries and may occasionally send marketing messages regarding new offers, promotions or services. Customers can opt-out of our SMS service at any time through their profile settings in the RealCar Connect application or website. If you experience any issues with our messaging service, you can contact our customer service at (212) 991-8002, or email us at hello@realcar.nyc. Please note that our carriers cannot be held responsible for any delays or failures in message delivery. Message and data rates may apply for any messages sent to or from RealCar Connect. The frequency of the messages may vary. If you have questions about your text or data plan, please consult with your wireless provider. For any queries or concerns related to privacy, please refer to our Privacy Policy, accessible here: Privacy Policy.`},
]

const TerrmsOfService = () => {
  return (
    <div className='max-w-7xl mx-auto p-15 md:p-25'>
        <div className='pb-5'><Title title="Rental Agreement - Terms of Service" className="text-2xl font-bold mb-4"/></div>
        <ol className='list-decimal ml-6'>
        {dataList.map((data,index)=>(
            <div key={index} className='text-justify gap-4 flex flex-col'>
                
                    <li className='font-bold text-lg mb-2'>{data.title}</li>
                    <p className='mb-4'>{data.content}</p>
                 
            </div>
        ))}
        </ol>
    </div>
  )
}

export default TerrmsOfService